services:
  app:
    build: .
    volumes:
      - .:/var/www/html       # live reload while editing
    ports:
      - "8000:8000"           # http://localhost:8000
    environment:
      APP_ENV: local
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      DB_FOREIGN_KEYS: "true"